main: fr.disneycraft.scores.Scores
name: DCScores
version: 1.0
author: tyhupo

commands:
    dcscores:
        description: Manage disneycraft scores
        usage: /<command> [commande] [joueur] [valeur]
        aliases: dcs